export default {
  SET_TAGS: 'SET_TAGS',
  FETCH_TAGS: 'FETCH_TAGS',
  SET_ARTICLES: 'SET_ARTICLES',
  FETCH_ARTICLES: 'FETCH_ARTICLES',
  SET_ARTICLE_DETAIL: 'SET_ARTICLE_DETAIL',
  FETCH_ARTICLE_DETAIL: 'FETCH_ARTICLE_DETAIL',
};
